import React, { useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { 
  Sparkles, 
  Image as ImageIcon, 
  Facebook, 
  Instagram, 
  Youtube, 
  Twitter, 
  CalendarDays,
  Send,
  Save,
  CheckCircle2,
  RefreshCw,
  Copy,
  ChevronDown
} from 'lucide-react';

export default function CreatePage() {
  const [searchParams] = useSearchParams();
  const mediaIdParam = searchParams.get('mediaId');
  const navigate = useNavigate();

  const [analyzing, setAnalyzing] = useState(false);
  const [analyzed, setAnalyzed] = useState(false);
  
  const [platform, setPlatform] = useState('facebook');
  const [language, setLanguage] = useState('English');
  const [tone, setTone] = useState('Casual');
  
  const [finalText, setFinalText] = useState('');

  const handleAnalyze = () => {
    setAnalyzing(true);
    // Simulate AI generation
    setTimeout(() => {
      setAnalyzing(false);
      setAnalyzed(true);
      setFinalText('Here is a great caption generated by AI! 🚀\n\nWhat do you think?\n\n#AI #Content #SocialMedia');
    }, 3000);
  };

  return (
    <div className="flex flex-col lg:flex-row gap-6 h-[calc(100vh-8rem)]">
      
      {/* LEFT PANEL: Setup & Controls */}
      <div className="w-full lg:w-[400px] xl:w-[450px] flex flex-col gap-4 overflow-y-auto pr-2 scrollbar-thin">
        
        {/* Media Selector */}
        <div className="bg-card border rounded-xl p-4 space-y-4">
          <h2 className="font-semibold text-sm uppercase text-muted-foreground tracking-wider">1. Select Media</h2>
          
          <div className="aspect-video bg-muted rounded-lg border-2 border-dashed border-border flex items-center justify-center flex-col gap-2 hover:border-brand-500 hover:bg-accent cursor-pointer transition-colors relative overflow-hidden group">
            {mediaIdParam ? (
              <>
                <img src="https://images.unsplash.com/photo-1517849845537-4d257902454a?w=800&q=80" alt="Selected" className="absolute inset-0 w-full h-full object-cover" />
                <div className="absolute inset-0 bg-black/50 opacity-0 group-hover:opacity-100 flex items-center justify-center transition-opacity">
                  <span className="text-white font-medium bg-black/50 px-4 py-2 rounded-lg">Change Media</span>
                </div>
              </>
            ) : (
              <>
                <div className="w-12 h-12 rounded-full bg-background flex items-center justify-center shadow-sm">
                  <ImageIcon className="w-6 h-6 text-muted-foreground" />
                </div>
                <span className="font-medium text-sm">Upload or Select Media</span>
              </>
            )}
          </div>
        </div>

        {/* Configuration */}
        <div className="bg-card border rounded-xl p-4 space-y-5 flex-1">
          <h2 className="font-semibold text-sm uppercase text-muted-foreground tracking-wider">2. Configuration</h2>
          
          {/* Platform */}
          <div className="space-y-2">
            <label className="text-sm font-medium">Platform</label>
            <div className="flex gap-2">
              <button onClick={() => setPlatform('facebook')} className={`p-2 rounded-lg border flex-1 flex justify-center items-center transition-colors ${platform === 'facebook' ? 'bg-[#1877F2] text-white border-[#1877F2]' : 'hover:bg-accent'}`}>
                <Facebook className="w-5 h-5" />
              </button>
              <button onClick={() => setPlatform('instagram')} className={`p-2 rounded-lg border flex-1 flex justify-center items-center transition-colors ${platform === 'instagram' ? 'bg-gradient-to-tr from-[#FD1D1D] to-[#405DE6] text-white border-transparent' : 'hover:bg-accent'}`}>
                <Instagram className="w-5 h-5" />
              </button>
              <button onClick={() => setPlatform('youtube')} className={`p-2 rounded-lg border flex-1 flex justify-center items-center transition-colors ${platform === 'youtube' ? 'bg-[#FF0000] text-white border-[#FF0000]' : 'hover:bg-accent'}`}>
                <Youtube className="w-5 h-5" />
              </button>
              <button onClick={() => setPlatform('tiktok')} className={`p-2 rounded-lg border flex-1 flex justify-center items-center transition-colors ${platform === 'tiktok' ? 'bg-black text-white dark:bg-white dark:text-black border-transparent' : 'hover:bg-accent'}`}>
                <svg className="w-5 h-5" viewBox="0 0 24 24" fill="currentColor"><path d="M19.59 6.69a4.83 4.83 0 0 1-3.77-4.25V2h-3.45v13.67a2.89 2.89 0 0 1-5.2 1.74 2.89 2.89 0 0 1 2.31-4.64 2.93 2.93 0 0 1 .88.13V9.4a6.84 6.84 0 0 0-1-.05A6.33 6.33 0 0 0 5 20.1a6.34 6.34 0 0 0 10.86-4.43v-7a8.16 8.16 0 0 0 4.77 1.52v-3.4a4.85 4.85 0 0 1-1.04-.1z"/></svg>
              </button>
              <button onClick={() => setPlatform('x')} className={`p-2 rounded-lg border flex-1 flex justify-center items-center transition-colors ${platform === 'x' ? 'bg-black text-white dark:bg-white dark:text-black border-transparent' : 'hover:bg-accent'}`}>
                <Twitter className="w-5 h-5" />
              </button>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <label className="text-sm font-medium">Language</label>
              <div className="relative">
                <select 
                  value={language}
                  onChange={(e) => setLanguage(e.target.value)}
                  className="w-full appearance-none bg-background border rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-brand-500 outline-none"
                >
                  <option>English</option>
                  <option>Hindi</option>
                  <option>Hinglish</option>
                  <option>Spanish</option>
                </select>
                <ChevronDown className="w-4 h-4 absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground pointer-events-none" />
              </div>
            </div>
            
            <div className="space-y-2">
              <label className="text-sm font-medium">Tone</label>
              <div className="relative">
                <select 
                  value={tone}
                  onChange={(e) => setTone(e.target.value)}
                  className="w-full appearance-none bg-background border rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-brand-500 outline-none"
                >
                  <option>Casual</option>
                  <option>Funny</option>
                  <option>Professional</option>
                  <option>Emotional</option>
                  <option>Viral</option>
                </select>
                <ChevronDown className="w-4 h-4 absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground pointer-events-none" />
              </div>
            </div>
          </div>

          <div className="pt-4 border-t mt-4">
            <button 
              onClick={handleAnalyze}
              disabled={analyzing}
              className="w-full py-3 rounded-lg font-bold text-white bg-gradient-brand shadow-md hover:shadow-lg transition-all flex justify-center items-center gap-2 disabled:opacity-80"
            >
              {analyzing ? (
                <>
                  <RefreshCw className="w-5 h-5 animate-spin" />
                  Generating AI Content...
                </>
              ) : (
                <>
                  <Sparkles className="w-5 h-5" />
                  ANALYZE & GENERATE
                </>
              )}
            </button>
          </div>
        </div>
      </div>

      {/* RIGHT PANEL: Generation Results & Final Post */}
      <div className="flex-1 flex flex-col gap-4 overflow-y-auto pr-2 scrollbar-thin">
        {!analyzed && !analyzing ? (
          <div className="h-full flex flex-col items-center justify-center text-center p-8 bg-card border rounded-xl border-dashed">
            <div className="w-20 h-20 rounded-full bg-brand-50 flex items-center justify-center text-brand-500 mb-6 shadow-inner">
              <Sparkles className="w-10 h-10" />
            </div>
            <h2 className="text-2xl font-bold mb-2">AI Content Studio</h2>
            <p className="text-muted-foreground max-w-md">
              Upload a photo or video, select your preferences, and let our AI analyze the content to generate optimized viral hooks, captions, and hashtags.
            </p>
          </div>
        ) : (
          <>
            {/* AI Results */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="bg-card border rounded-xl p-4 space-y-4">
                <h3 className="font-semibold flex items-center gap-2 text-brand-600">
                  <Sparkles className="w-4 h-4" /> AI Engagement Score
                </h3>
                <div className="flex items-center gap-6">
                  <div className="relative w-24 h-24 flex items-center justify-center shrink-0">
                    <svg className="w-full h-full transform -rotate-90">
                      <circle cx="48" cy="48" r="40" stroke="currentColor" strokeWidth="8" fill="transparent" className="text-muted" />
                      <circle cx="48" cy="48" r="40" stroke="currentColor" strokeWidth="8" fill="transparent" strokeDasharray="251.2" strokeDashoffset={251.2 - (251.2 * 92) / 100} className="text-green-500 transition-all duration-1000 ease-out" />
                    </svg>
                    <div className="absolute flex flex-col items-center">
                      <span className="text-2xl font-bold">92</span>
                      <span className="text-[10px] text-muted-foreground font-medium uppercase tracking-wider">Score</span>
                    </div>
                  </div>
                  <div className="flex-1 space-y-2 text-sm">
                    <div className="flex justify-between"><span className="text-muted-foreground">Hook Strength</span><span className="font-medium text-green-500">High</span></div>
                    <div className="flex justify-between"><span className="text-muted-foreground">Emotion</span><span className="font-medium text-blue-500">Medium</span></div>
                    <div className="flex justify-between"><span className="text-muted-foreground">Shareability</span><span className="font-medium text-green-500">High</span></div>
                  </div>
                </div>
              </div>

              <div className="bg-card border rounded-xl p-4 space-y-3">
                <h3 className="font-semibold flex items-center gap-2">Hashtags</h3>
                <div className="flex flex-wrap gap-2">
                  {['#dogs', '#puppylove', '#cutedogs', '#viral', '#foryou', '#dogsofinstagram'].map(tag => (
                    <span key={tag} className="px-2 py-1 bg-accent text-accent-foreground rounded-md text-xs font-medium cursor-pointer hover:bg-brand-100 hover:text-brand-700 transition-colors">
                      {tag}
                    </span>
                  ))}
                </div>
                <button className="text-xs text-brand-600 font-medium hover:underline flex items-center gap-1 mt-2">
                  <Copy className="w-3 h-3" /> Copy All Hashtags
                </button>
              </div>
            </div>

            {/* Captions Options */}
            <div className="bg-card border rounded-xl p-4 space-y-4">
              <h3 className="font-semibold flex items-center gap-2">
                Generated Captions
              </h3>
              <div className="space-y-3">
                {[
                  { type: 'Best Overall', text: 'Who can resist those puppy eyes? 🥺 Tag someone who needs a smile today! \n\n#puppylove #cutedogs' },
                  { type: 'Funny', text: 'My dog judging me for eating my 3rd snack of the day... 🐶👀 \n\n#dogslife #funnydogs' }
                ].map((cap, i) => (
                  <div key={i} className="p-3 border rounded-lg hover:border-brand-300 transition-colors cursor-pointer" onClick={() => setFinalText(cap.text)}>
                    <div className="flex justify-between items-center mb-1">
                      <span className="text-xs font-medium bg-accent px-2 py-0.5 rounded text-muted-foreground">{cap.type}</span>
                    </div>
                    <p className="text-sm whitespace-pre-wrap">{cap.text}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Final Post Editor */}
            <div className="bg-card border-2 border-brand-500/20 rounded-xl overflow-hidden flex flex-col flex-1 min-h-[300px]">
              <div className="p-3 bg-brand-50 border-b border-brand-100 flex justify-between items-center">
                <h3 className="font-semibold text-brand-800">Final Post Content</h3>
              </div>
              <textarea 
                className="w-full flex-1 p-4 resize-none outline-none bg-background text-sm leading-relaxed"
                value={finalText}
                onChange={(e) => setFinalText(e.target.value)}
                placeholder="Select a caption above or start typing..."
              />
              
              {/* Publish Controls inside the editor block */}
              <div className="p-4 border-t bg-muted/30 flex flex-col sm:flex-row gap-4 sm:items-end justify-between">
                
                <div className="space-y-2 flex-1">
                  <label className="text-xs font-medium text-muted-foreground">Destinations</label>
                  <div className="flex flex-wrap gap-2">
                    <label className="flex items-center gap-2 bg-background border px-3 py-1.5 rounded-lg text-sm cursor-pointer hover:border-brand-500">
                      <input type="checkbox" defaultChecked className="accent-brand-600 rounded" />
                      <Facebook className="w-4 h-4 text-blue-600" />
                      My Main Page
                    </label>
                  </div>
                </div>

                <div className="flex flex-wrap gap-2 justify-end shrink-0">
                  <button className="px-4 py-2 bg-background border hover:bg-accent rounded-lg text-sm font-medium transition-colors flex items-center gap-2">
                    <Save className="w-4 h-4" /> Draft
                  </button>
                  <button className="px-4 py-2 bg-background border hover:bg-accent rounded-lg text-sm font-medium transition-colors flex items-center gap-2">
                    <CalendarDays className="w-4 h-4 text-orange-500" /> Schedule
                  </button>
                  <button className="px-4 py-2 bg-brand-600 hover:bg-brand-700 text-white rounded-lg text-sm font-medium transition-colors flex items-center gap-2">
                    <Send className="w-4 h-4" /> Publish Now
                  </button>
                </div>
              </div>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
